language: python
python:
  - 3.7
  - 3.8
# PyPy versions
  - "pypy3"
install:
  - pip install -r requirements.txt
script:
  - python tests/test_imagecache.py
os:
  - windows
  - linux
  - osx